-- Create the roles
create role apps_role;
create role admin_role;
create role cs_user in role apps_role;
alter role cs_user with password 'cs123' login;
create role auth_user in role apps_role;
alter role auth_user with password 'cs123' login;
create role cap_user in role apps_role;
alter role cap_user with password 'cs123' login;
create role rav_user in role apps_role;
alter role rav_user with password 'cs123' login;
create role se_user in role apps_role;
alter role se_user with password 'cs123' login;
create role rss_user in role apps_role;
alter role rss_user with password 'cs123' login;
create role autocomplete_user in role apps_role;
alter role autocomplete_user with password 'cs123' login;
create role cs_compare_user in role apps_role;
alter role cs_compare_user with password 'cs123' login;
create role cs_quote_user in role apps_role;
alter role cs_quote_user with password 'cs123' login;
create role cs_preferences_service in role apps_role;
alter role cs_preferences_service with password 'cs123' login;
create role cs_cms_service in role apps_role;
alter role cs_cms_service with password 'cs123' login;
create role cs_admin_service in role apps_role;
alter role cs_admin_service with password 'cs123' login;
create role cs_permission_service in role apps_role;
alter role cs_permission_service with password 'cs123' login;
create role cs_umbrella_backend in role apps_role;
alter role cs_umbrella_backend with password 'cs123' login;

create role af;
create role am;
create role bd;
create role jg;
create role gb;
create role joc;
create role jr2;
create role rs;
create role ss;
create role st;
create role aj;
create role ap;
create role "as";
create role gg;
create role gp;
create role "hestia-integration-test-user";
create role if;
create role jr;
create role kv;
create role lv;
create role mt;
create role pt;
create role rg;
create role rl;
create role sc;
create role sd;
create role ta;
create role vs;
create role yz;
create role lh;
grant all on all tables in schema public to apps_role;
grant all on all sequences in schema public to apps_role;
grant all on database local to  apps_role;
grant all on  schema public to apps_role;
